import type { PromptConfig, TestCase } from "../components/EvalContext";

/**
 * Export the current UI config + test cases as a `suite.yaml` that the
 * EvalLayer CLI can run unchanged:  evallayer run suite.yaml
 *
 * This is the bridge between the demo UI and eval-as-code / CI. The schema
 * matches backend/app/cli.py's loader exactly (provider/model/prompt/
 * run_config/runs/judge/cases with a `checks` list per case).
 *
 * Strings are emitted via JSON.stringify, which produces valid YAML
 * double-quoted scalars (YAML shares JSON's escape syntax), so multi-line
 * system prompts and quotes survive a round-trip safely.
 */

function q(s: string | undefined): string {
  return JSON.stringify(s ?? "");
}

function checksFor(tc: TestCase): string[] {
  const checks: string[] = [];
  if (tc.strict) checks.push("strict");
  if (tc.allowNormalized) checks.push("normalised");
  if (tc.useLLMCheck) checks.push("llm");
  return checks.length ? checks : ["normalised"];
}

export function toSuiteYaml(prompt: PromptConfig, testCases: TestCase[]): string {
  const lines: string[] = [];
  lines.push("# Generated by the EvalLayer UI — run with:  evallayer run suite.yaml");
  lines.push(`name: ${q(prompt.name)}`);
  lines.push(`provider: ${q(prompt.provider ?? "huggingface")}`);
  lines.push(`model: ${q(prompt.modelName)}`);
  lines.push("prompt:");
  lines.push(`  system_prompt: ${q(prompt.systemPrompt)}`);
  lines.push(`  user_template: ${q(prompt.userTemplate || "{input}")}`);
  lines.push("run_config:");
  lines.push(`  temperature: ${prompt.temperature}`);
  lines.push(`  max_tokens: ${prompt.maxTokens}`);
  lines.push(`runs: ${prompt.runsPerCase ?? 1}`);
  if (prompt.judgeModelName) {
    lines.push("judge:");
    lines.push(`  provider: ${q(prompt.judgeProvider ?? "huggingface")}`);
    lines.push(`  model: ${q(prompt.judgeModelName)}`);
  }
  lines.push("cases:");
  testCases.forEach((tc, i) => {
    lines.push(`  - name: ${q(`case-${i + 1}`)}`);
    lines.push(`    input: { input: ${q(tc.input)} }`);
    lines.push(`    expected: ${q(tc.expectedOutput)}`);
    lines.push(`    checks: [${checksFor(tc).join(", ")}]`);
  });
  return lines.join("\n") + "\n";
}

export function downloadSuiteYaml(prompt: PromptConfig, testCases: TestCase[]): void {
  const yaml = toSuiteYaml(prompt, testCases);
  const blob = new Blob([yaml], { type: "text/yaml;charset=utf-8;" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = "suite.yaml";
  link.click();
  URL.revokeObjectURL(link.href);
}
